# -*- coding: utf-8 -*-
"""IDS Assign-1(SP20-BCS-087)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18fPK5GDC0-Gzl7uGwDOm--4YHWYUtGy4
"""

import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/Ebookhttps://en.wikipedia.org/wiki/Ebook"
r = requests.get(url)

r.content

root = BeautifulSoup(r.content, 'html5lib')
print(root.prettify())

table = root.find('table')
print(table)

for i in table.find_all('div', attrs = {'class':'plainlist'}):
  print (table.get_text())

div = table.find('img') 
print(div)

for item in div.findAll('a', attrs = {'id':'extiw'}): 
  print(div)

extract = table.find('ul')
print(extract)

reextract = extract.findAll('li')

for items in extract.findAll('li'): 
 lists = (extract.get_text())
 print(lists)

soup = BeautifulSoup(r.text, 'html.parser')
table = soup.find_all('h3',attrs={'class':"vector-menu-heading "})
array = []
for i in table:
 data = i.text.replace('\n', ' ').strip()
 array.append(data)
for q in array:
 print(q)

